Adopt OS and LAT mirrors
Establish separate OS and LAT mirrors to allow the upstream use of
Debian repos with a StarlingX LAT mirror for the LAT SDK

Changes Include:
 - Read and check the current key/values of stx.conf to make sure that
   there are some sane values when running stx-init-env
 - Add OS_MIRROR_URL, OS_MIRROR_DIST_PATH, LAT_MIRROR_URL,
   LAT_MIRROR_LAT_PATH for maximum flexibility in defining mirror
   configurations as different mirrors may be structured
   differently (official stx mirror vs. upstream debian vs. local
   mirror)
 - Pass mirror configuration to the container builds
 - Drop old migration support for snapshots and cengn as this transition
   should be completed during previous releases

Test Plan:
 - PASS: stx-init-env --rebuild, downloader, build-pkgs -a, build-image

Prototype: Concurrent Builds in master

Change-Id: I13cc11a433d3dfa4ecacc8675d91890b8ae3adda
Story: NNNNNNN
Task: NNNNN
Signed-off-by: Robert Church <robert.church@windriver.com>
Signed-off-by: Scott Little <scott.little@windriver.com>

diff --git a/stx-init-env b/stx-init-env
--- a/stx-init-env
+++ b/stx-init-env
@@ -85,6 +85,8 @@ RESET_HARD=0
 ASSUME_YES=0
 STX_START_OPTS=
 
+# An image that contains the gnu 'rm' command.  
+# It doesn't need to track the build target (e.g. bullseye/trixie)
 COREUTILS_DOCKER_IMAGE="debian:bookworm-20240130-slim"
 
 info() {
@@ -394,12 +396,6 @@ safe_rm() {
         echo "running: ${rm_cmd[*]}" >&2
         "${rm_cmd[@]}" || exit 1
     done
-}
-
-init_stx_mirror_url() {
-    if [[ -z "$STX_MIRROR_URL" && -f "$STX_TOOLS_DIR/stx.conf" ]] ; then
-        STX_MIRROR_URL=$(sed -n -r 's/^\s*stx_mirror_url\s*=\s*//gp'  "$STX_TOOLS_DIR/stx.conf" | sed "s/[\"']//g")
-    fi
 }
 
 cmdline_error() {
@@ -715,6 +711,55 @@ if [[ "$DOCKERHUB_LOGIN" -eq 1 ]] ; then
     STX_START_OPTS+=" --use-dockerhub-cred"
 fi
 
+## We should a valid stx.conf file here, read it and get the distro
+if [[ ! -f "$STX_TOOLS_DIR/stx.conf" ]] ; then
+    error "$STX_TOOLS_DIR/stx.conf: file not found. Run with the '--clean' option first to use the latest stx.conf sample"
+    exit 1
+fi
+
+# set an associative array
+declare -A STX_CONF
+
+# remove comments and build a section.key=value string for reading and storing
+while IFS='=' read -r key value; do
+    echo "$key:$value"
+    STX_CONF[$(echo $key | xargs)]="$(echo $value | xargs)"
+done < <(cat $STX_TOOLS_DIR/stx.conf | grep -v ^# | awk '/^\[/ { section=substr($0,2,length-2) } /=/ { print section "." $0 }')
+
+# Get the config values to pass to the the container builds
+dist=${STX_CONF["builder.dist"]}
+os_mirror_url=${STX_CONF["repomgr.os_mirror_url"]}
+os_mirror_dist_path=${STX_CONF["repomgr.os_mirror_dist_path"]}
+lat_mirror_url=${STX_CONF["repomgr.lat_mirror_url"]}
+lat_mirror_lat_path=${STX_CONF["repomgr.lat_mirror_lat_path"]}
+
+# bail if values are missing
+if [ -z "${dist}" ]; then
+    error "Missing stx.conf value for: builder.dist"
+    exit 1
+fi
+if [ -z "${os_mirror_url}" ]; then \
+    error "Missing stx.conf value for: repomgr.os_mirror_url"
+    exit 1
+fi
+if [ -z "${os_mirror_dist_path}" ]; then
+    error "Missing stx.conf value for: repomgr.os_mirror_dist_path"
+    exit 1
+fi
+if [ -z "${lat_mirror_url}" ]; then
+    error "Missing stx.conf value for: repomgr.lat_mirror_url"
+    exit 1
+fi
+
+if [ -z "${lat_mirror_lat_path}" ]; then
+    error "Missing stx.conf value for: repomgr.lat_mirror_lat_path"
+    exit 1
+fi
+
+echo "Setup for distro: $dist:"
+echo "  - OS mirror: ${os_mirror_url}${os_mirror_dist_path}"
+echo "  - LAT mirror: ${lat_mirror_url}${lat_mirror_lat_path}"
+
 # Workaround: Wait for Minikube network to stabilize before building images
 sleep 10
 
@@ -724,22 +769,23 @@ if [[ -n "${BUILD_DOCKER_IMAGES}" ]] ; then
     if [[ "$USE_DOCKER_CACHE" != "1" ]] ; then
         docker_build_args+=("--no-cache")
     fi
+
+    extra_build_args=()
+    extra_build_args+=("--build-arg")
+    extra_build_args+=("os_mirror_url=$os_mirror_url")
+    extra_build_args+=("--build-arg")
+    extra_build_args+=("os_mirror_dist_path=$os_mirror_dist_path")
+    extra_build_args+=("--build-arg")
+    extra_build_args+=("lat_mirror_url=$lat_mirror_url")
+    extra_build_args+=("--build-arg")
+    extra_build_args+=("lat_mirror_lat_path=$lat_mirror_lat_path")
+
     for img in $BUILD_DOCKER_IMAGES; do
-        info "Starting to build image: $img:$DOCKER_TAG_LOCAL"
-
-        extra_build_args=()
-        if grep -q -E '^\s*ARG\s+STX_MIRROR_URL\s*=' "$STX_TOOLS_DIR/"stx/dockerfiles/$img.Dockerfile ; then
-            init_stx_mirror_url
-            if [[ -n "$STX_MIRROR_URL" ]] ; then
-                extra_build_args+=("--build-arg" "STX_MIRROR_URL=$STX_MIRROR_URL")
-            fi
-        fi
-
-        cmd="docker build "${docker_build_args[@]}" "${extra_build_args[@]}" -t $img:$DOCKER_TAG_LOCAL -f "$STX_TOOLS_DIR/"stx/dockerfiles/$img.Dockerfile "$STX_TOOLS_DIR""
+        info "Starting to build image: $img:$DOCKER_TAG_LOCAL-${dist}"
+        cmd="docker build "${docker_build_args[@]}" "${extra_build_args[@]}" -t $img:$DOCKER_TAG_LOCAL-${dist} -f "$STX_TOOLS_DIR/"stx/dockerfiles/${dist}/$img.Dockerfile "$STX_TOOLS_DIR""
         info "Running command: ${cmd}"
         eval "$cmd" || exit 1
-
-        info "Finished building image: $img:$DOCKER_TAG_LOCAL"
+        info "Finished building image: $img:$DOCKER_TAG_LOCAL-${dist}"
     done
 fi
 
@@ -754,7 +800,7 @@ PULL_DOCKER_IMAGES=$(
             fi
         done
         if [[ "$built" != "yes" ]] && \
-            { [[ "$USE_DOCKER_CACHE" != 1 ]] || ! docker image inspect ${img}:${DOCKER_TAG_LOCAL} >/dev/null 2>&1 ; } ; then
+            { [[ "$USE_DOCKER_CACHE" != 1 ]] || ! docker image inspect ${img}:${DOCKER_TAG_LOCAL}-${dist} >/dev/null 2>&1 ; } ; then
             echo "$img"
         fi
     done
@@ -762,9 +808,9 @@ PULL_DOCKER_IMAGES=$(
 if [[ -n "$PULL_DOCKER_IMAGES" ]] ; then
     notice "Pulling docker images: "$PULL_DOCKER_IMAGES
     for img in $PULL_DOCKER_IMAGES; do
-        docker pull ${DOCKER_PREFIX}${img}:${DOCKER_TAG} || exit 1
-        docker tag ${DOCKER_PREFIX}${img}:${DOCKER_TAG} ${img}:${DOCKER_TAG_LOCAL} || exit 1
-        info "created image ${img}:${DOCKER_TAG_LOCAL} from pre-built ${DOCKER_PREFIX}${img}:${DOCKER_TAG}"
+        docker pull ${DOCKER_PREFIX}${img}:${DOCKER_TAG}-${dist} || exit 1
+        docker tag ${DOCKER_PREFIX}${img}:${DOCKER_TAG} ${img}:${DOCKER_TAG_LOCAL}-${dist} || exit 1
+        info "created image ${img}:${DOCKER_TAG_LOCAL}-${dist} from pre-built ${DOCKER_PREFIX}${img}:${DOCKER_TAG}-${dist}"
     done
 fi
 
